version: "3"
services:
    #
    # The mongo database dockerfile
    #
    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip_all

    #
    # The express server dockerfile
    #
    express:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/bankerydare
        volumes:
            # - ./:/app/
            - ./:/app/
            # - /app/node_modules/
            - /app/node_modules/
        ports:
            - 3000:3000
        links:
            - mongodb
        command: "npm start"

    node90:
        image: "node:9.0.0"
        user: "node"
        ports:
            - "8071:3000"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app/
        command: "npm start"
    node80:
        image: node:8.0.0
        ports:
            - "8070:3000"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app/
        command: "npm start"
    node70:
        image: node:7.0.0
        ports:
            - "8056:3000"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app/
        command: "npm start"

    # Here comes some for test

    node_7:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-7
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"

    node_6:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-6
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"

    node_5:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-5
        volumes:
            - ./:/app/
        ports:
            - "3000:3000"
